version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  geek-text-api:
    build: ./server
    ports:
      - 3001:3001
    depends_on: 
      - mongo
  geek-text-web:
    build: ./client
    ports:
      - 80:80
    depends_on:
      - geek-text-api

